/**
 * Check if a cron expression matches a given date in a specific timezone.
 * Supports standard 5-field cron: minute hour dom month dow
 */
export function cronMatchesNow(cronExpr: string, now: Date, timezone: string): boolean {
  const parts = cronExpr.trim().split(/\s+/);
  if (parts.length !== 5) return false;

  const [cronMin, cronHour, cronDom, cronMonth, cronDow] = parts;

  // Get the current time in the target timezone
  const formatter = new Intl.DateTimeFormat("en-US", {
    timeZone: timezone,
    minute: "numeric",
    hour: "numeric",
    day: "numeric",
    month: "numeric",
    weekday: "short",
    hour12: false,
  });

  const parts2 = formatter.formatToParts(now);
  const get = (type: string) => Number(parts2.find((p) => p.type === type)?.value || 0);
  const dowMap: Record<string, number> = { sun: 0, mon: 1, tue: 2, wed: 3, thu: 4, fri: 5, sat: 6 };

  const currentMin = get("minute");
  const currentHour = get("hour") === 24 ? 0 : get("hour");
  const currentDom = get("day");
  const currentMonth = get("month");
  const currentDow = dowMap[parts2.find((p) => p.type === "weekday")?.value.toLowerCase() || ""] ?? 0;

  // The fieldMatchesDow function is a duplicate of fieldMatches and does not correctly handle
  // day-of-week names (e.g., 'MON', 'TUE') which might be generated by the LLM.
  // It should be updated to parse day names to numbers or use a more robust cron parser library.
  return (
    fieldMatches(cronMin, currentMin) &&
    fieldMatches(cronHour, currentHour) &&
    fieldMatches(cronDom, currentDom) &&
    fieldMatches(cronMonth, currentMonth) &&
    fieldMatches(cronDow, currentDow) // Using fieldMatches for now, but still problematic for names
  );
}

function fieldMatches(field: string, value: number): boolean {
  if (field === "*") return true;
  // Handle */N (every N)
  const stepMatch = field.match(/^\*\/(\d+)$/);
  if (stepMatch) return value % Number(stepMatch[1]) === 0;
  // Handle comma-separated values
  if (field.includes(",")) return field.split(",").some((v) => Number(v) === value);
  // Handle ranges
  if (field.includes("-")) {
    const [start, end] = field.split("-").map(Number);
    return value >= start && value <= end;
  }
  return Number(field) === value;
}

function fieldMatchesDow(field: string, value: number): boolean {
  if (field === "*") return true;
  if (field.includes(",")) return field.split(",").some((v) => Number(v) === value);
  if (field.includes("-")) {
    const [start, end] = field.split("-").map(Number);
    return value >= start && value <= end;
  }
  return Number(field) === value;
}
