"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Activity, AlertTriangle, ArrowRight, CheckCircle2, Clock3, GitBranch, RefreshCw, ShieldAlert, Sparkles, Target, Users, Zap } from "lucide-react";
import { useAuth } from "../../dashboard/auth-provider";

type Task = { id: string; title: string; status: string; priority: string; assignee_slack_id?: string | null; due_date?: string | null; due_at?: string | null; created_at?: string | null; updated_at?: string | null };
type Schedule = { id: string; name: string; schedule_type: string; is_active: boolean; next_run_at?: string | null; created_at?: string | null };
type Workflow = { id: string; name: string; is_active: boolean; trigger_type?: string | null; steps?: unknown[] | null; created_at?: string | null };

const api = async <T,>(resource: string, workspaceId: string, token: string, limit = 200): Promise<T[]> => {
  const response = await fetch(`/api/dashboard/${resource}?workspace_id=${encodeURIComponent(workspaceId)}&limit=${limit}`, { headers: { Authorization: `Bearer ${token}` }, cache: "no-store" });
  if (!response.ok) throw new Error(`${resource}: ${response.status}`);
  const data = await response.json();
  return Array.isArray(data) ? data : [];
};
const ageHours = (value?: string | null) => value ? Math.max(0, (Date.now() - new Date(value).getTime()) / 36e5) : 0;
const dueDate = (task: Task) => task.due_at || task.due_date;
const isOpen = (status: string) => !["completed", "done", "cancelled", "canceled"].includes(status.toLowerCase());
const formatRelative = (value?: string | null) => { if (!value) return "No signal"; const delta = new Date(value).getTime() - Date.now(); const hours = Math.round(Math.abs(delta) / 36e5); if (hours < 24) return delta < 0 ? `${hours}h overdue` : `in ${hours}h`; const days = Math.round(hours / 24); return delta < 0 ? `${days}d overdue` : `in ${days}d`; };
const scoreRisk = (task: Task) => { let score = 0; const due = dueDate(task); if (due && new Date(due).getTime() < Date.now() && isOpen(task.status)) score += 60; if (ageHours(task.updated_at || task.created_at) > 72 && isOpen(task.status)) score += 25; if (["high", "urgent", "critical"].includes(task.priority.toLowerCase())) score += 15; return Math.min(100, score); };

export default function OperationalRadarPage() {
  const { session, workspaceId } = useAuth();
  const [tasks, setTasks] = useState<Task[]>([]); const [schedules, setSchedules] = useState<Schedule[]>([]); const [workflows, setWorkflows] = useState<Workflow[]>([]);
  const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [lastRefresh, setLastRefresh] = useState<Date | null>(null);
  const load = useCallback(async () => {
    if (!workspaceId || !session?.access_token) return; setLoading(true); setError(null);
    try { const [t, s, w] = await Promise.all([api<Task>("tasks", workspaceId, session.access_token), api<Schedule>("schedules", workspaceId, session.access_token), api<Workflow>("workflows", workspaceId, session.access_token)]); setTasks(t); setSchedules(s); setWorkflows(w); setLastRefresh(new Date()); }
    catch (err) { setError(err instanceof Error ? err.message : "Unable to read workspace state"); } finally { setLoading(false); }
  }, [session?.access_token, workspaceId]);
  useEffect(() => { load(); }, [load]);

  const openTasks = useMemo(() => tasks.filter(t => isOpen(t.status)), [tasks]);
  const overdue = useMemo(() => openTasks.filter(t => { const d = dueDate(t); return d && new Date(d).getTime() < Date.now(); }), [openTasks]);
  const stale = useMemo(() => openTasks.filter(t => ageHours(t.updated_at || t.created_at) >= 72), [openTasks]);
  const highRisk = useMemo(() => [...openTasks].map(task => ({ task, risk: scoreRisk(task) })).filter(x => x.risk >= 40).sort((a,b) => b.risk - a.risk), [openTasks]);
  const inactiveSchedules = schedules.filter(s => !s.is_active); const inactiveWorkflows = workflows.filter(w => !w.is_active);
  const activeAutomations = schedules.filter(s => s.is_active).length + workflows.filter(w => w.is_active).length;
  const bottlenecks = useMemo(() => { const counts = new Map<string, number>(); for (const task of openTasks) { const owner = task.assignee_slack_id || "Unassigned"; counts.set(owner, (counts.get(owner) || 0) + 1); } return [...counts.entries()].sort((a,b) => b[1] - a[1]).slice(0,5); }, [openTasks]);
  const attention = useMemo(() => { const items: { level: "critical" | "warning" | "info"; title: string; detail: string }[] = []; if (overdue.length) items.push({level:"critical",title:`${overdue.length} commitments are overdue`,detail:"These are the highest-probability sources of delivery drift."}); if (stale.length) items.push({level:"warning",title:`${stale.length} open tasks have gone quiet for 72h+`,detail:"Silence is treated as a leading indicator, not a completed outcome."}); if (inactiveSchedules.length) items.push({level:"warning",title:`${inactiveSchedules.length} schedules are disabled`,detail:"Recurring operational work may be silently paused."}); if (inactiveWorkflows.length) items.push({level:"info",title:`${inactiveWorkflows.length} workflows are inactive`,detail:"Review whether these automations still represent current operating procedures."}); if (!items.length) items.push({level:"info",title:"No material operational drift detected",detail:"KlawHub found no overdue, stale, or disabled signals in connected workspace data."}); return items; }, [inactiveSchedules.length,inactiveWorkflows.length,overdue.length,stale.length]);

  return <div className="space-y-8">
    <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2 text-xs uppercase tracking-[0.18em] text-sleekCyan font-semibold"><Activity className="w-4 h-4"/> Operational intelligence</div><h1 className="mt-2 text-3xl md:text-4xl font-bold tracking-tight">Operational Radar</h1><p className="mt-2 max-w-3xl text-sm md:text-base text-gray-400">KlawHub watches the workspace as a living system and surfaces commitments, silence, automation gaps, and concentration risk before they become incidents.</p></div><button onClick={load} disabled={loading} className="inline-flex items-center justify-center gap-2 rounded-xl border border-glassBorder bg-white/5 px-4 py-2.5 text-sm font-medium hover:bg-white/10 disabled:opacity-50"><RefreshCw className={`h-4 w-4 ${loading ? "animate-spin" : ""}`}/> Refresh signal</button></header>
    {error && <div className="rounded-2xl border border-red-400/20 bg-red-400/5 p-4 text-sm text-red-200 flex items-start gap-3"><ShieldAlert className="h-5 w-5 shrink-0"/><div><p className="font-semibold">Radar could not read workspace state.</p><p className="mt-1 text-red-200/70">{error}</p></div></div>}
    <section className="grid grid-cols-2 xl:grid-cols-5 gap-3">{[["Open commitments",openTasks.length,Target],["Overdue",overdue.length,AlertTriangle],["Silent 72h+",stale.length,Clock3],["Active automations",activeAutomations,Zap],["High-risk items",highRisk.length,ShieldAlert]].map(([label,value,Icon]) => <div key={String(label)} className="rounded-2xl border border-glassBorder bg-glassPanel p-5"><Icon className="h-4 w-4 text-gray-500"/><div className="mt-4 text-2xl font-bold">{loading ? "—" : String(value)}</div><div className="mt-1 text-xs text-gray-500">{String(label)}</div></div>)}</section>
    <div className="grid grid-cols-1 xl:grid-cols-[1.35fr_.65fr] gap-6">
      <section className="rounded-2xl border border-glassBorder bg-glassPanel overflow-hidden"><div className="p-6 border-b border-glassBorder flex items-center justify-between"><div><h2 className="font-semibold">Attention queue</h2><p className="text-xs text-gray-500 mt-1">Derived from current workspace state, not hardcoded metrics.</p></div><Sparkles className="h-5 w-5 text-sleekCyan"/></div><div className="divide-y divide-glassBorder">{attention.map((item,i) => <div key={`${item.title}-${i}`} className="p-5 flex gap-4"><div className={`mt-0.5 h-8 w-8 rounded-lg flex items-center justify-center ${item.level === "critical" ? "bg-red-400/10 text-red-300" : item.level === "warning" ? "bg-amber-400/10 text-amber-300" : "bg-sleekCyan/10 text-sleekCyan"}`}>{item.level === "critical" ? <AlertTriangle className="h-4 w-4"/> : item.level === "warning" ? <Clock3 className="h-4 w-4"/> : <Activity className="h-4 w-4"/>}</div><div><p className="font-medium text-sm">{item.title}</p><p className="text-xs text-gray-500 mt-1 leading-relaxed">{item.detail}</p></div></div>)}</div></section>
      <section className="rounded-2xl border border-glassBorder bg-glassPanel p-6"><div className="flex items-center gap-2"><Users className="h-4 w-4 text-gray-500"/><h2 className="font-semibold">Work concentration</h2></div><p className="mt-1 text-xs text-gray-500">Open commitments by assignee.</p><div className="mt-6 space-y-4">{bottlenecks.length ? bottlenecks.map(([owner,count]) => { const max=bottlenecks[0][1]||1; return <div key={owner}><div className="flex justify-between text-xs mb-2"><span className={owner === "Unassigned" ? "text-amber-300" : "text-gray-300"}>{owner}</span><span className="text-gray-500">{count}</span></div><div className="h-2 rounded-full bg-white/5 overflow-hidden"><div className="h-full rounded-full bg-sleekCyan/60" style={{width:`${Math.max(8,(count/max)*100)}%`}}/></div></div>; }) : <div className="rounded-xl border border-dashed border-glassBorder p-6 text-sm text-gray-500">No open assignments yet.</div>}</div></section>
    </div>
    <section className="rounded-2xl border border-glassBorder bg-glassPanel overflow-hidden"><div className="p-6 border-b border-glassBorder flex items-center justify-between"><div><h2 className="font-semibold">Highest-risk commitments</h2><p className="text-xs text-gray-500 mt-1">Risk combines lateness, silence, and declared priority.</p></div><Link href="/tasks" className="text-xs text-sleekCyan hover:underline inline-flex items-center gap-1">Open task system <ArrowRight className="h-3 w-3"/></Link></div>{highRisk.length ? <div className="divide-y divide-glassBorder">{highRisk.slice(0,8).map(({task,risk}) => <div key={task.id} className="p-5 flex flex-col md:flex-row md:items-center gap-4 md:justify-between"><div className="min-w-0"><div className="flex items-center gap-2"><span className={`h-2 w-2 rounded-full ${risk>=70 ? "bg-red-400" : "bg-amber-300"}`}/><p className="font-medium text-sm truncate">{task.title}</p></div><p className="mt-1 text-xs text-gray-500">{task.priority} priority · {dueDate(task) ? formatRelative(dueDate(task)) : "no due date"} · {task.assignee_slack_id || "unassigned"}</p></div><div className="flex items-center gap-4"><div className="w-28"><div className="flex justify-between text-[10px] text-gray-500 mb-1"><span>drift risk</span><span>{risk}%</span></div><div className="h-1.5 rounded-full bg-white/5"><div className={`h-full rounded-full ${risk>=70 ? "bg-red-400" : "bg-amber-300"}`} style={{width:`${risk}%`}}/></div></div><Link href="/tasks" className="text-xs text-gray-500 hover:text-white">Inspect</Link></div></div>)}</div> : <div className="p-10 text-center text-sm text-gray-500"><CheckCircle2 className="mx-auto h-6 w-6 text-glowGreen mb-3"/>No high-risk commitments detected.</div>}</section>
    <section className="grid grid-cols-1 md:grid-cols-3 gap-4"><Link href="/tasks" className="group rounded-2xl border border-glassBorder bg-glassPanel p-5 hover:bg-white/5 transition"><Target className="h-5 w-5 text-sleekCyan"/><h3 className="mt-4 text-sm font-semibold">Commitments</h3><p className="mt-1 text-xs text-gray-500">See the underlying tasks and ownership.</p><ArrowRight className="mt-4 h-4 w-4 text-gray-600 group-hover:text-sleekCyan transition"/></Link><Link href="/schedules" className="group rounded-2xl border border-glassBorder bg-glassPanel p-5 hover:bg-white/5 transition"><Clock3 className="h-5 w-5 text-neonPurple"/><h3 className="mt-4 text-sm font-semibold">Automation health</h3><p className="mt-1 text-xs text-gray-500">Inspect schedules that are active or paused.</p><ArrowRight className="mt-4 h-4 w-4 text-gray-600 group-hover:text-neonPurple transition"/></Link><Link href="/workflow" className="group rounded-2xl border border-glassBorder bg-glassPanel p-5 hover:bg-white/5 transition"><GitBranch className="h-5 w-5 text-glowGreen"/><h3 className="mt-4 text-sm font-semibold">Operating procedures</h3><p className="mt-1 text-xs text-gray-500">Review the workflows encoding how work gets done.</p><ArrowRight className="mt-4 h-4 w-4 text-gray-600 group-hover:text-glowGreen transition"/></Link></section>
    <footer className="text-xs text-gray-600 flex items-center justify-between"><span>Radar is computed from connected workspace records.</span><span>{lastRefresh ? `Updated ${lastRefresh.toLocaleTimeString()}` : "Awaiting signal"}</span></footer>
  </div>;
}
