import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";

export const metadata = {
  title: "Terms of Service | Klawhub AI Coworker",
  description: "Terms and conditions of using Klawhub autonomous agent and coworker services.",
};

export default function TermsOfService() {
  return (
    <>
      <Header />
      <main className="relative overflow-hidden pt-32 pb-20 lg:pt-40 lg:pb-32 min-h-screen bg-surface-50">
        <div className="pointer-events-none absolute inset-0">
          <div className="absolute -top-40 -right-40 h-[500px] w-[500px] rounded-full bg-brand-200/20 blur-3xl" />
          <div className="absolute top-1/2 left-1/2 h-[400px] w-[400px] -translate-x-1/2 -translate-y-1/2 rounded-full bg-purple-200/10 blur-3xl" />
        </div>

        <div className="relative mx-auto max-w-4xl px-6">
          <div className="rounded-2xl border border-surface-200 bg-white p-8 md:p-12 shadow-xl shadow-surface-100/50">
            <h1 className="text-3xl font-extrabold tracking-tight text-surface-900 sm:text-4xl">
              Terms of Service
            </h1>
            <p className="mt-2 text-sm text-surface-500">
              Last Updated: May 6, 2026
            </p>

            <div className="mt-8 border-t border-surface-100 pt-8 prose prose-slate max-w-none text-surface-700 space-y-6">
              <p className="leading-relaxed">
                Welcome to <strong>Klawhub</strong>! These Terms of Service (&quot;Terms&quot;) govern your use of Klawhub&apos;s website, applications, and autonomous agent services located at <a href="https://klawhub.xyz" className="text-brand-600 hover:underline">klawhub.xyz</a>.
              </p>

              <p className="leading-relaxed">
                By accessing or using Klawhub, you agree to comply with and be bound by these Terms. If you do not agree, please do not use our services.
              </p>

              <hr className="border-surface-100" />

              <section className="space-y-3">
                <h2 className="text-xl font-bold text-surface-900">1. Description of Services</h2>
                <p className="leading-relaxed">
                  Klawhub operates an autonomous, multi-agent AI coworker system that connects directly to your team&apos;s Slack channels. The system enables users to trigger agent-driven builds, document writing, multi-step search research, and database-driven data analytics.
                </p>
              </section>

              <section className="space-y-3">
                <h2 className="text-xl font-bold text-surface-900">2. Workspace Integrity & Authorized Access</h2>
                <p className="leading-relaxed">
                  When integrating Klawhub with third-party systems (such as Slack, Google Drive, or GitHub), you represent and warrant that you possess proper administrative permissions or authorization within your organization to connect these integrations. Klawhub accepts no liability for unauthorized workspace integrations triggered by standard users.
                </p>
              </section>

              <section className="space-y-3">
                <h2 className="text-xl font-bold text-surface-900">3. Multi-Agent AI & Build Approvals</h2>
                <p className="leading-relaxed">
                  Certain high-value operations executed by Klawhub (such as code builds or document briefs) utilize an integrated human-in-the-loop approval gate. It is the user&apos;s responsibility to review, modify, and authorize these specifications before Klawhub continues running its execution pipelines.
                </p>
              </section>

              <section className="space-y-3">
                <h2 className="text-xl font-bold text-surface-900">4. Third-Party Integrations & Google API Scopes</h2>
                <p className="leading-relaxed">
                  Your use of Klawhub integrations with Google Drive, Gmail, and Google Calendar is subject to the respective Google Terms of Service. Klawhub processes calendar schedules and document text ephemerally to compile briefing packages. It is your responsibility to maintain compliance with your organization&apos;s data policies when sharing documentation with Klawhub agents.
                </p>
              </section>

              <section className="space-y-3">
                <h2 className="text-xl font-bold text-surface-900">5. Limitation of Liability</h2>
                <p className="leading-relaxed">
                  While we strive to provide highly robust, error-tested AI workflows, all Klawhub services are provided &quot;as is&quot; and &quot;as available.&quot; We make no representations or warranties that the code, specs, research reports, or emails generated by Klawhub are flawless, complete, or entirely secure for critical business environments. You assume full responsibility for validating agent results prior to deployment.
                </p>
              </section>

              <section className="space-y-3">
                <h2 className="text-xl font-bold text-surface-900">6. Termination</h2>
                <p className="leading-relaxed">
                  We reserve the right to suspend or terminate your access to Klawhub immediately, without prior notice, if you violate any of these Terms, engage in excessive API spam, or use our agents to compile malicious, fraudulent, or abusive scripts.
                </p>
              </section>

              <section className="space-y-3">
                <h2 className="text-xl font-bold text-surface-900">7. Changes to Terms</h2>
                <p className="leading-relaxed">
                  We reserve the right to revise or update these Terms at any time. We will publish changes directly on this page, updating the &quot;Last Updated&quot; date at the top. Continued usage of Klawhub after terms modification represents your active acceptance.
                </p>
              </section>

              <section className="space-y-3">
                <h2 className="text-xl font-bold text-surface-900">8. Contact Us</h2>
                <p className="leading-relaxed">
                  If you have any questions or require clarifications regarding these Terms of Service, please reach out to us:
                </p>
                <p className="text-sm font-semibold text-surface-900">
                  Email: <a href="mailto:support@klawhub.xyz" className="text-brand-600 hover:underline">support@klawhub.xyz</a>
                </p>
              </section>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
